In [73]:
import pandas as pd

In [74]:
stats = pd.read_csv("player_mvp_stats.csv", index_col=0)

In [75]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,0.484,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,0.286,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,0.470,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,0.459,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,0.455,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [76]:
# A little bit of Data cleaning

In [77]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          50
3P            0
3PA           0
3P%        2042
2P            0
2PA           0
2P%          84
eFG%         50
FT            0
FTA           0
FT%         462
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [78]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]]

                 Player  3PA
2        Elden Campbell  0.0
3         Irving Thomas  0.0
18           Jack Haley  0.0
20          Keith Owens  0.0
30      Benoit Benjamin  0.0
...                 ...  ...
14061    Evan Eschmeyer  0.0
14062  Gheorghe Mureșan  0.0
14064     Jim McIlvaine  0.0
14070  Mark Hendrickson  0.0
14071      Michael Cage  0.0

[2042 rows x 2 columns]

In [79]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]]

                Player  FTA
77          John Coker  0.0
92        Jason Sasser  0.0
103    Adrian Caldwell  0.0
119       Bruno Šundov  0.0
158     Jamal Robinson  0.0
...                ...  ...
13951    Mark McNamara  0.0
13979      Luke Zeller  0.0
14032      Myron Brown  0.0
14054      Malcolm Lee  0.0
14088      Steve Novak  0.0

[462 rows x 2 columns]

In [80]:
stats = stats.fillna(0)

In [81]:
# Training ML model

In [82]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [83]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']

In [84]:
train = stats[stats["Year"] < 2021]

In [85]:
test = stats[stats["Year"] == 2021]

In [86]:
test.Share.unique()

array([0.   , 0.961, 0.138, 0.01 , 0.02 , 0.449, 0.001, 0.005, 0.038,
       0.003, 0.58 , 0.345, 0.042, 0.008])

In [87]:
from sklearn.linear_model import Ridge

In [88]:
reg = Ridge(alpha=.1)

In [89]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [90]:
predictions = reg.predict(test[predictors])

In [91]:
predictions

array([ 1.35668109e-02, -1.37555982e-02,  2.41422426e-03, -4.42094230e-03,
        1.07344594e-02, -4.23959177e-03,  1.33565106e-02,  4.20436903e-02,
       -1.33305361e-03,  5.42262069e-02,  2.35442671e-03,  1.54306069e-01,
       -8.23356517e-03,  1.58906678e-02, -9.51591532e-03, -1.75032468e-03,
       -7.53739544e-03, -7.76823755e-03, -1.56383251e-02, -1.31177504e-02,
       -4.11721314e-03,  5.17866825e-02, -1.03275631e-02,  8.91408407e-02,
        1.05931994e-02, -1.24192715e-02,  4.54456704e-04, -1.89454285e-02,
       -3.61395333e-03,  5.68796286e-03, -1.98298194e-02, -4.03365357e-03,
        3.91548356e-02,  2.69110750e-02,  1.65422868e-02,  1.42850143e-02,
        2.03627535e-03, -1.51729788e-02, -4.43059444e-03,  3.42219680e-02,
       -2.37992674e-02,  3.42648695e-04,  6.72437186e-02,  8.81183851e-02,
        4.46785909e-02,  2.09652204e-03,  6.91475933e-03, -1.20338052e-02,
        3.00914678e-02, -3.91651499e-02, -1.67019335e-02, -1.39033510e-03,
       -2.28864132e-03, -1.94050368e-02,  7.09735225e-03, -1.13500639e-04,
        2.01092111e-02,  7.22933798e-02,  9.92434258e-03,  3.30437620e-02,
        7.52354136e-02, -1.80071417e-02,  1.79426698e-02,  6.08838036e-03,
       -3.68246602e-03,  6.53592166e-03, -4.41062025e-04,  1.27788910e-02,
        4.60236511e-04,  7.78717260e-03, -3.15601920e-03, -2.05976326e-02,
       -8.27140615e-04, -3.59326349e-03,  5.12934135e-03, -5.81782786e-03,
       -1.24749831e-03, -3.66550883e-02, -1.65053538e-02,  1.76353212e-02,
        8.54197492e-02, -2.54233680e-02, -1.90685363e-03,  2.95105198e-02,
       -2.03750748e-03, -1.85804407e-02,  9.11362969e-02,  3.93663805e-02,
       -2.73074640e-02, -3.15133515e-02,  3.64315898e-03,  1.58505365e-02,
       -3.51326449e-04, -6.28124653e-03, -2.76546649e-03, -1.95563577e-02,
       -8.50994565e-03, -3.47348707e-03, -8.65793434e-03,  1.21896610e-02,
        6.24937491e-03,  9.30011186e-02, -1.55409770e-03, -1.57924699e-02,
        9.41999239e-03,  2.70161638e-03,  1.91764641e-02,  3.30005976e-02,
       -1.03896068e-02, -3.41670580e-04,  2.05670168e-02,  1.88276541e-02,
        8.88771089e-02, -7.37513532e-03, -1.26610643e-02, -1.41204821e-02,
       -7.02825105e-03,  2.91381908e-03,  7.95971927e-03, -1.38751832e-02,
       -1.29402364e-02,  2.17289423e-02, -3.88718072e-03,  2.84267392e-02,
        3.19807623e-04,  2.29817797e-02,  1.00717175e-02, -1.74524560e-03,
        8.34558390e-03, -1.95298936e-02,  1.80046508e-02,  9.52907980e-04,
        1.46325852e-02,  2.05627834e-03, -2.78260863e-02,  1.98264791e-02,
        5.35134929e-04, -6.75345480e-03,  1.42385804e-01, -3.23140871e-03,
        2.02188095e-03,  5.36111436e-02,  9.71552080e-02, -3.02681009e-03,
        1.71005396e-02, -5.34786375e-04,  3.22991921e-03, -1.66721504e-02,
        6.75950353e-03, -5.81719006e-04,  1.47511539e-01,  7.76027310e-03,
       -4.50040432e-03,  5.01791741e-02,  1.16459068e-02, -1.76632278e-02,
       -1.60888408e-03, -1.23110594e-02, -6.23990170e-02,  1.02510525e-01,
       -7.78913785e-03, -2.08054345e-02,  8.39905140e-03, -2.65047635e-02,
       -7.91997039e-03, -1.54741924e-02, -2.95844155e-02, -9.04073807e-03,
       -3.50724788e-02, -8.53742593e-03, -1.15742443e-02, -1.44466916e-02,
        1.20227312e-01,  2.25928267e-02,  8.10884580e-03, -2.69070903e-02,
        1.17451340e-02,  3.65538737e-03,  7.04719780e-03,  9.05788054e-03,
       -5.86025434e-03,  1.40597812e-01,  5.43053884e-03, -2.80725062e-03,
        1.41350380e-01,  1.00830282e-01,  1.54902785e-02, -1.11903248e-02,
        1.87751263e-03,  9.31207334e-03,  6.42900385e-03, -1.22838417e-02,
       -2.32027804e-03, -1.82324703e-02, -1.72679001e-02, -3.69212238e-03,
       -1.10498488e-02,  3.16078778e-02,  6.13068761e-03, -3.65553696e-02,
        1.13349841e-01, -6.43803991e-03,  4.69719378e-03,  4.21777222e-03,
       -2.15648461e-03, -6.90459217e-03, -6.99153453e-03,  7.54786065e-02,
       -9.05229445e-04,  6.90432900e-03,  2.09382133e-02, -5.37921591e-03,
        5.61716809e-03,  1.13486576e-02, -2.96727862e-03, -9.66945613e-03,
        5.00003297e-02, -1.25516198e-02, -2.85341630e-02,  4.99453869e-03,
       -7.36803962e-03, -8.83051388e-03, -4.83222514e-02,  1.50369322e-04,
        3.79859685e-02, -9.33533119e-03,  3.62581381e-02, -8.29716187e-03,
       -6.01046145e-03,  3.09148600e-03, -1.95472835e-02, -3.17198782e-04,
        2.54170540e-03, -6.69440280e-04, -5.89790428e-03, -4.96418849e-03,
        8.01942676e-02,  2.06052083e-02, -3.69070790e-03, -1.07471160e-02,
        1.24887141e-02,  1.17101857e-01, -1.65047057e-02,  9.48478179e-03,
        6.10814778e-03,  5.89407117e-03,  6.56122236e-03,  4.37039911e-03,
       -5.88341399e-03,  1.58112815e-02,  1.28927243e-02,  4.98037784e-02,
       -1.51901731e-03, -5.51765414e-03,  5.67460347e-02,  7.43997309e-03,
        1.16302652e-01, -1.96499523e-02,  2.08348471e-02, -1.27276345e-03,
        3.98890802e-02, -5.91743589e-03, -1.21665161e-02,  2.29389220e-02,
       -1.00961213e-02, -4.91814827e-03, -1.18278732e-02,  1.88464850e-02,
        7.13167847e-03,  4.54209307e-02, -2.55863123e-02, -2.72000787e-02,
       -1.08261103e-02, -6.74747227e-03, -1.99288189e-02, -5.56019315e-03,
       -1.23247137e-02, -2.75479394e-02,  7.61092247e-03,  9.26306181e-02,
        9.86063424e-03,  2.98765844e-02,  9.85116514e-03, -3.52753565e-02,
       -2.15503371e-02, -4.12793180e-02, -9.05037724e-03,  2.24382346e-02,
       -1.43640674e-02,  8.24643203e-02, -6.62878754e-03, -3.67785959e-03,
       -3.16916874e-02, -1.78383026e-02, -4.06427685e-03,  2.40602260e-02,
       -8.00288603e-03,  4.53195370e-02, -2.10841878e-02,  2.64060505e-02,
       -6.19340658e-03,  5.31136293e-03,  3.34759199e-02, -3.07381464e-02,
       -2.55178463e-02, -6.99678040e-03,  6.25369598e-02, -1.83120810e-03,
       -7.26226926e-03,  2.57034736e-02,  6.31683799e-03, -2.40398840e-02,
       -2.41347344e-03, -1.07296620e-03,  1.62712958e-01,  1.57092427e-02,
       -1.12981419e-02, -1.32291681e-02,  2.67364986e-03,  5.77306176e-03,
       -5.48584061e-03,  1.44741968e-02,  4.34755206e-03,  6.37023371e-02,
        7.64861405e-03,  2.99097454e-03, -2.41440187e-02,  5.10999787e-02,
       -1.65898392e-02,  3.26401564e-02, -2.85406737e-02, -1.49416113e-02,
        5.84587953e-03, -3.94238736e-03, -2.31772032e-02,  3.32665491e-02,
       -7.72520524e-03,  1.24326725e-02,  4.84956654e-02, -5.03440765e-02,
       -1.05574311e-02, -3.73676032e-02, -1.55067291e-02, -9.51657545e-03,
       -7.07647784e-03,  2.03572735e-02,  8.66179148e-03, -5.93934877e-03,
       -9.03212513e-03, -2.62270916e-02,  2.07436261e-01,  4.31347045e-04,
       -9.50396301e-03,  3.25618212e-03,  4.52525111e-02, -1.15494343e-02,
        4.84902891e-02, -3.88048485e-03, -5.49950578e-02, -1.06074690e-02,
       -6.55798624e-03, -7.58613150e-03, -1.61152885e-02, -2.16491763e-02,
       -8.79261094e-03, -5.22781950e-03, -1.77365539e-02,  1.43048821e-02,
        1.52924813e-02,  4.11019063e-02, -4.84376989e-03, -1.14610394e-02,
        4.04122456e-02,  4.86716687e-03,  7.17686778e-03,  6.89827266e-04,
       -1.09360714e-02,  6.79170434e-03,  3.89826286e-02, -9.39944352e-03,
        5.86837027e-03, -2.90320632e-02, -1.05661324e-03, -1.92791038e-03,
        2.21479569e-02, -1.76050205e-02, -1.97109302e-02,  5.94671904e-02,
        1.51430048e-01, -2.23020669e-02,  4.06349682e-03, -7.84168888e-03,
        2.31127646e-02, -2.34498335e-03, -1.03316856e-02,  3.37806986e-03,
       -6.34671026e-03,  2.37566377e-02, -6.93102279e-03, -1.33998810e-02,
       -2.31780583e-02,  6.57988806e-02,  2.49470960e-02,  1.59055771e-02,
        4.41185369e-02, -9.54244744e-03, -2.98502927e-02,  4.28164642e-03,
        2.22248424e-04, -1.07537824e-02, -3.94166042e-04, -3.08440510e-02,
       -3.47057094e-02,  9.99117152e-02,  1.32179835e-02,  6.74395854e-03,
        7.87287584e-02,  6.80947574e-03,  1.61889853e-03, -2.84435677e-03,
       -1.68723526e-03,  2.21793820e-02,  3.80804656e-02, -6.95736735e-03,
        1.14336061e-03,  4.41212229e-02, -1.09763863e-02, -2.55058593e-02,
        9.53501878e-02, -9.23861261e-03, -3.39137946e-03,  1.17940044e-02,
        7.11718234e-03, -1.30884049e-02, -5.67891464e-03, -2.29114517e-03,
        5.16366689e-02,  3.64846449e-02, -6.04453873e-03,  6.00151237e-02,
       -7.91237675e-03, -1.78013984e-02, -9.33390345e-03,  4.27059945e-02,
       -1.91598228e-02, -6.97891942e-03,  3.03285091e-03, -3.38412514e-03,
        6.14206458e-02, -6.95419420e-02, -1.07241476e-03, -4.23801424e-02,
       -5.80621110e-03, -1.29108202e-04, -3.38100094e-03,  1.83332083e-03,
       -1.83651132e-02,  1.57856733e-02,  3.05775171e-03,  2.24401396e-03,
       -2.17444689e-02, -2.14368001e-02, -2.84808765e-02, -1.12283221e-02,
        6.79184528e-03,  1.27926379e-01,  5.46587556e-03,  1.46831270e-03,
       -2.41556547e-02, -1.35107290e-02,  1.00762580e-01,  8.52662586e-03,
       -2.58127421e-02,  2.14123690e-02,  2.93731297e-02, -8.32679754e-03,
       -1.61676831e-03, -2.71108335e-03,  1.25038476e-02,  1.46942517e-02,
       -2.23461636e-02,  3.83061898e-02,  8.83157947e-04,  2.87585228e-03,
        5.58405569e-03, -2.37833820e-02, -1.88589449e-02, -5.43253091e-03,
       -5.08769929e-03,  1.94926787e-03, -1.67727911e-02, -3.20250469e-02,
       -3.55215330e-02, -3.06915875e-02, -1.46373813e-02, -1.78170411e-02,
       -2.25142311e-02, -1.48179309e-02, -1.77021272e-02,  2.07437497e-02,
        6.08421033e-04,  5.85897945e-03, -4.37942035e-03, -5.56549846e-03,
       -1.38246476e-02,  8.37994441e-03,  1.48233113e-02, -6.57342130e-03,
       -2.99877405e-03, -2.49487207e-03, -4.83892461e-03,  1.63773872e-02,
       -9.97705933e-03, -1.50981088e-02,  4.71739896e-02,  7.91823196e-03,
       -5.13160671e-02,  2.91103574e-02, -8.95874471e-03, -3.13496926e-04,
       -3.23346075e-03, -2.46169341e-02, -2.32868011e-02, -6.94279147e-03,
        8.18164562e-02,  3.22060773e-02,  1.71860352e-02, -1.31103079e-02,
       -4.64228692e-03,  1.31513905e-02,  1.19366539e-03, -6.79360909e-03,
       -1.74815058e-04, -1.93682367e-02, -4.99666560e-03, -1.25708949e-02,
       -1.15751459e-02,  1.64240886e-02, -2.04342787e-02, -5.42092226e-03])

In [92]:
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [93]:
predictions

       predictions
630       0.013567
631      -0.013756
632       0.002414
633      -0.004421
634       0.010734
...            ...
13897    -0.012571
13898    -0.011575
13899     0.016424
13900    -0.020434
13901    -0.005421

[540 rows x 1 columns]

In [94]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [95]:
# combination

In [96]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions
641             Nikola Jokić  0.961     0.154306
8624             Joel Embiid  0.580     0.162713
3651           Stephen Curry  0.449     0.142386
9907   Giannis Antetokounmpo  0.345     0.207436
1389              Chris Paul  0.138     0.072293
10997            Luka Dončić  0.042     0.151430
7464          Damian Lillard  0.038     0.116303
3536           Julius Randle  0.020     0.088877
3531            Derrick Rose  0.010     0.033001
11358            Rudy Gobert  0.008     0.095350

In [97]:
# Identifying an error metric

In [98]:
from sklearn.metrics import mean_squared_error as mse

In [99]:
mse(combination["Share"], combination["predictions"])

0.0026668960013828697

In [100]:
combination["Share"].value_counts()

0.000    525
0.001      3
0.961      1
0.138      1
0.010      1
0.020      1
0.449      1
0.005      1
0.038      1
0.003      1
0.580      1
0.345      1
0.042      1
0.008      1
Name: Share, dtype: int64

In [101]:
combination = combination.sort_values("Share", ascending=False)
combination["Rk"] = list(range(1, combination.shape[0]+1))

In [102]:
combination.head(10)

                      Player  Share  predictions  Rk
641             Nikola Jokić  0.961     0.154306   1
8624             Joel Embiid  0.580     0.162713   2
3651           Stephen Curry  0.449     0.142386   3
9907   Giannis Antetokounmpo  0.345     0.207436   4
1389              Chris Paul  0.138     0.072293   5
10997            Luka Dončić  0.042     0.151430   6
7464          Damian Lillard  0.038     0.116303   7
3536           Julius Randle  0.020     0.088877   8
3531            Derrick Rose  0.010     0.033001   9
11358            Rudy Gobert  0.008     0.095350  10

In [103]:
combination = combination.sort_values("predictions", ascending=False)
combination["Predicted_Rk"] = list(range(1, combination.shape[0]+1))

In [104]:
combination.head(10)

                      Player  Share  predictions   Rk  Predicted_Rk
9907   Giannis Antetokounmpo  0.345     0.207436    4             1
8624             Joel Embiid  0.580     0.162713    2             2
641             Nikola Jokić  0.961     0.154306    1             3
10997            Luka Dončić  0.042     0.151430    6             4
3736            LeBron James  0.001     0.147512   15             5
3651           Stephen Curry  0.449     0.142386    3             6
4177            Kevin Durant  0.000     0.141350  531             7
4174            James Harden  0.001     0.140598   13             8
11784        Zion Williamson  0.000     0.127926  251             9
3876       Russell Westbrook  0.005     0.120227   11            10

In [105]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions  Rk  Predicted_Rk
641             Nikola Jokić  0.961     0.154306   1             3
8624             Joel Embiid  0.580     0.162713   2             2
3651           Stephen Curry  0.449     0.142386   3             6
9907   Giannis Antetokounmpo  0.345     0.207436   4             1
1389              Chris Paul  0.138     0.072293   5            33
10997            Luka Dončić  0.042     0.151430   6             4
7464          Damian Lillard  0.038     0.116303   7            12
3536           Julius Randle  0.020     0.088877   8            24
3531            Derrick Rose  0.010     0.033001   9            76
11358            Rudy Gobert  0.008     0.095350  10            19

In [106]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found/seen)
        seen += 1
    return sum(ps) / len(ps)

In [107]:
find_ap(combination)

0.7636363636363636

In [108]:
# Implementing backtesting to predict each year

In [109]:
years = list(range(1991, 2022))

In [110]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors], train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [111]:
sum(aps) / len(aps)

0.7112884360789578

In [112]:
def add_ranks(combination):
    combination = combination.sort_values("Share", ascending=False)
    combination["Rk"] = list(range(1, combination.shape[0]+1))
    combination = combination.sort_values("predictions", ascending=False)
    combination["Predicted_Rk"] = list(range(1, combination.shape[0]+1))
    combination["Diff"] = combination["Rk"] - combination["Predicted_Rk"]
    return combination

In [113]:
ranking = add_ranks(all_predictions[1])
ranking[ranking["Rk"] < 6].sort_values("Diff", ascending=False)

               Player  Share  predictions  Rk  Predicted_Rk  Diff
1600      Karl Malone  0.857     0.192318   1             2    -1
10524  Michael Jordan  0.832     0.167629   2             3    -1
908        Grant Hill  0.327     0.128646   3             6    -3
4682     Tim Hardaway  0.207     0.059984   4            20   -16
8248        Glen Rice  0.117     0.033110   5            53   -48

In [114]:
def backtest(stats, model, year, predictors):
    aps = []
    all_predictions = []
    for year in years[5:]:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors], train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps)/len(aps), aps, pd.concat(all_predictions)

In [115]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [116]:
mean_ap

0.7112884360789578

In [117]:
# Diagnosing model performance

In [118]:
all_predictions[all_predictions["Rk"] <= 5].sort_values("Diff").head(10)

                 Player  Share  predictions  Rk  Predicted_Rk  Diff
1224         Jason Kidd  0.712     0.028210   2            52   -50
8248          Glen Rice  0.117     0.033110   5            53   -48
5175         Steve Nash  0.839     0.034100   1            45   -44
8516    Peja Stojaković  0.228     0.036270   4            38   -34
5193         Steve Nash  0.739     0.054129   1            34   -33
12726       Joakim Noah  0.258     0.046968   4            37   -33
3657   Chauncey Billups  0.344     0.052696   5            35   -30
1389         Chris Paul  0.138     0.072293   5            33   -28
5208         Steve Nash  0.785     0.074421   2            21   -19
4682       Tim Hardaway  0.207     0.059984   4            20   -16

In [119]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.070001  eFG%
18  0.035041   DRB
29  0.027125  W/L%
17  0.021610   ORB
10  0.016945    2P
21  0.011635   STL
15  0.011351   FTA
22  0.011234   BLK
20  0.007455   AST
25  0.005894   PTS
4   0.005694    FG
5   0.005517   FGA
7   0.004569    3P
12  0.004083   2P%
0   0.000321   Age
30  0.000270    GB
27  0.000098     W
1   0.000092     G
2  -0.000006    GS
26 -0.000184  Year
32 -0.000219  PA/G
28 -0.000295     L
33 -0.000521   SRS
31 -0.000556  PS/G
24 -0.002635    PF
3  -0.004150    MP
16 -0.004575   FT%
14 -0.006586    FT
23 -0.009696   TOV
9  -0.009822   3P%
8  -0.010395   3PA
11 -0.017319   2PA
19 -0.027506   TRB
6  -0.135024   FG%

In [120]:
# Adding more predictors

In [121]:
stat_ratios = stats[['PTS', 'AST', 'STL', 'BLK', '3P', 'Year']].groupby('Year').apply(lambda x: x/x.mean())

C:\Users\Zhibek Zhagypar\AppData\Local\Temp\ipykernel_368\611064546.py:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  stat_ratios = stats[['PTS', 'AST', 'STL', 'BLK', '3P', 'Year']].groupby('Year').apply(lambda x: x/x.mean())

In [122]:
stats[['PTS_T', 'AST_R', 'STL_R', 'BLK_R', '3P_R']] = stat_ratios[['PTS', 'AST', 'STL', 'BLK', '3P']]

In [123]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,PTS_T,AST_R,STL_R,BLK_R,3P_R
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.707,5.0,106.3,99.6,6.73,1.013334,0.420714,0.961127,0.673469,0.508587
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0.707,5.0,106.3,99.6,6.73,1.614653,1.028412,1.647646,0.673469,4.577279
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0.707,5.0,106.3,99.6,6.73,0.311795,0.093492,0.274608,1.571429,0.000000
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0.707,5.0,106.3,99.6,6.73,0.200440,0.186984,0.274608,0.000000,0.000000
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0.707,5.0,106.3,99.6,6.73,2.383005,1.636110,1.784950,0.897959,1.525760

In [124]:
predictors += ['PTS_T', 'AST_R', 'STL_R', 'BLK_R', '3P_R']

In [125]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [126]:
mean_ap

0.7208380973034985

In [127]:
stats['NPos'] = stats['Pos'].astype('category').cat.codes

In [128]:
stats['NTm'] = stats['Tm'].astype('category').cat.codes

In [129]:
stats['Pos'].unique()

array(['PF', 'SG', 'SF', 'PG', 'C', 'PG-SG', 'PF-SF', 'SG-PG', 'PF-C',
       'SG-SF', 'SF-PF', 'SF-SG', 'C-PF', 'SG-PF', 'PG-SF', 'SF-C'],
      dtype=object)

In [130]:
# Using Random Forest model

In [131]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors)

In [132]:
mean_ap

0.7160867351429451

In [133]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [134]:
mean_ap

0.7208380973034985